version: "3"
services:
  app:
    image: node:14.20-alpine
    command: yarn start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
  mysql:
    image: mariadb
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=secret
      - MYSQL_DATABASE=blindpiano

  pma:
    image: phpmyadmin/phpmyadmin:edge-4.8
    ports:
      - "4001:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
    restart: always
    depends_on:
      - mysql
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mysql-volume:
