module.exports = {
  WAITING_PLAYERS: "WAITING_PLAYERS",
  PRE_TURN: "PRE_TURN",
  RUNNING: "RUNNING",
  FINISHED: "FINISHED",
  LEARNING_SONG: "LEARNING_SONG",
  PLAY_SONG: "PLAY_SONG",
  SCORE_SCREEN: "SCORE_SCREEN",
};
