module.exports = {
  WAITING_PLAYERS: "WAITING_PLAYERS",
  PRE_TURN: "PRE_TURN",
  RUNNING: "RUNNING",
  FINISHED: "FINISHED",
  LEARNING_SONG: "LEARNING_SONG",
  PLAY_SONG: "PLAY_SONG",
  SCORES_SCREEN: "SCORES_SCREEN",
  FINAL_SCREEN: "FINAL_SCREEN",
  RESPONSE_SCREEN: "RESPONSE_SCREEN",
};
