module.exports = {
  WAITING_PLAYERS_SCREEN: "WAITING_PLAYERS_SCREEN",
  PRE_TURN_SCREEN: "PRE_TURN_SCREEN",
  RUNNING: "RUNNING",
  FINISHED: "FINISHED",
  LEARNING_SONG_SCREEN: "LEARNING_SONG_SCREEN",
  CHOOSE_SONG_SCREEN: "CHOOSE_SONG_SCREEN",
  PLAY_SONG_SCREEN: "PLAY_SONG_SCREEN",
  SCORES_SCREEN: "SCORES_SCREEN",
  FINAL_SCREEN: "FINAL_SCREEN",
  RESPONSE_SCREEN: "RESPONSE_SCREEN",
};
